version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.16.0
    commands:
      - echo "Installing dependencies..."
      - ls -lrt
      - npm ci

  build:
    commands:
      - echo "Building the application..."
      - npm run test

artifacts:
  files:
    - '**/*'
  discard-paths: no
